// Generated by Dazl before every dev-server start - do not edit.
// Wraps the app's own vite config with Dazl's plugins (the @dazl/dev JSX runtime, the preview
// client and the editor's page manifest) so the repository needs no Dazl-specific changes. Dazl's
// launcher passes this file to vite with -c; a startDev hook receives its path as DAZL_VITE_CONFIG.
import { createRequire } from "node:module";
import dazlPlugins from "../../../dazl-ai/dist/dazl-plugin.js";
// the app has no vite config file of its own
const originalConfig = {};

// the APP's vite version (not the engine's): the plugin picks its JSX transform by major version
const appRequire = createRequire("/usr/session/package.json");
let viteVersion;
try {
  viteVersion = appRequire("vite/package.json").version;
} catch {
  // vite is not resolvable from the app root; the plugin falls back to its default transform
}

export default async (env) => {
  const userConfig =
    (typeof originalConfig === "function" ? await originalConfig(env) : await originalConfig) ?? {};
  const userPlugins =
    userConfig.plugins === undefined ? [] : Array.isArray(userConfig.plugins) ? userConfig.plugins : [userConfig.plugins];
  const plugins = await dazlPlugins({ viteVersion, previewScriptUrl: process.env.DAZL_PREVIEW_SCRIPT_URL });
  return { ...userConfig, plugins: [...userPlugins, ...plugins] };
};
