// Generated by Dazl before every dev-server start - do not edit.
// Wraps the app's own vite config with Dazl's plugins (the @dazl/dev JSX runtime, the preview
// client and the editor's page manifest) so the repository needs no Dazl-specific changes. Dazl's
// launcher passes this file to vite with -c; a startDev hook receives its path as DAZL_VITE_CONFIG.
import { createRequire } from "node:module";
import dazlPlugins from "../../../dazl-ai/dist/dazl-plugin.js";
// the app has no vite config file of its own
const originalConfig = {};

// the APP's vite version (not the engine's): the plugin picks its JSX transform by major version
const appRequire = createRequire("/usr/session/package.json");
let viteVersion;
try {
  viteVersion = appRequire("vite/package.json").version;
} catch {
  // vite is not resolvable from the app root; the plugin falls back to its default transform
}

export default async (env) => {
  const userConfig =
    (typeof originalConfig === "function" ? await originalConfig(env) : await originalConfig) ?? {};
  const userPlugins =
    userConfig.plugins === undefined ? [] : Array.isArray(userConfig.plugins) ? userConfig.plugins : [userConfig.plugins];
  const plugins = await dazlPlugins({ viteVersion, previewScriptUrl: process.env.DAZL_PREVIEW_SCRIPT_URL });
  const config = { ...userConfig, plugins: [...userPlugins, ...plugins] };
  // Dazl's preview proxy owns the public port, so this server's port is private and is pinned here
  // too, not only via the CLI --port flag - this wrapper is what a repo's own vite config passes
  // through last, so the CLI flag alone could still be undone by userConfig.server.port above. Set
  // only when Dazl launched this dev server itself: a startDev hook never gets this env var, so
  // this block no-ops for one and the port the hook reported back to Dazl stands unchanged.
  // strictPort is forced off so a repo that set it auto-increments off a busy port instead of
  // turning a second local editor into a hard EADDRINUSE exit.
  const dazlPort = Number(process.env.DAZL_DEV_SERVER_PORT);
  if (Number.isInteger(dazlPort) && dazlPort > 0) {
    config.server = { ...userConfig.server, port: dazlPort, strictPort: false };
  }
  return config;
};
