// Generated by dazl/scripts/dazl-in-dazl/install.mjs — edit the installer, not this file.
// Runs with cwd = the app root (<root>/dazl). Node builtins only: no node_modules resolve from here.
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';

const APP_ROOT = process.cwd();
const ROOT = path.resolve(APP_ROOT, '..');
const INSTALLER = path.join(APP_ROOT, 'scripts', 'dazl-in-dazl', 'install.mjs');
const WEB_PORT = 4444;

const env = (extra: Record<string, string | undefined> = {}) => {
    const e: Record<string, string | undefined> = { ...process.env, NODE_ENV: 'development', ...extra };
    // the outer session's port pins must not reach the inner Dazl
    delete e['DAZL_STRICT_PORT'];
    delete e['DAZL_DESKTOP_ENABLED'];
    return e;
};

const readEnvFile = (file: string) => {
    const out: Record<string, string> = {};
    if (!fs.existsSync(file)) return out;
    for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
        const m = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
        if (m) out[m[1]!] = m[2]!.replace(/^"(.*)"$/, '$1').replace(/\s+#.*$/, '');
    }
    return out;
};

const runToEnd = (cmd: string, args: string[], cwd = APP_ROOT) =>
    new Promise<number>((resolve) => {
        const child = spawn(cmd, args, { cwd, env: env(), stdio: 'inherit' });
        child.on('error', (err) => {
            console.error(`[dazl.hooks] ${cmd} failed to start: ${err.message}`);
            resolve(-1);
        });
        child.on('exit', (code) => resolve(code ?? -1));
    });

const portOpen = (port: number) =>
    new Promise<boolean>((resolve) => {
        const s = net.connect({ port, host: 'localhost', autoSelectFamily: true });
        s.once('connect', () => { s.destroy(); resolve(true); });
        s.once('error', () => resolve(false));
        s.setTimeout(1500, () => { s.destroy(); resolve(false); });
    });

const mustSucceed = async (label: string, cmd: string, args: string[]) => {
    const code = await runToEnd(cmd, args);
    if (code !== 0) throw new Error(`[dazl.hooks] ${label} failed: ${cmd} ${args.join(' ')} exited ${code}`);
};

export async function installDependencies() {
    if (!fs.existsSync(path.join(APP_ROOT, 'node_modules', '.bin', 'react-router'))) {
        await mustSucceed('npm ci', 'npm', ['ci', '--include=dev']);
    }
}

export async function addDependencies({ deps, isDev }: { deps: string[]; isDev: boolean }) {
    await mustSucceed('npm install', 'npm', ['install', ...(isDev ? ['--save-dev'] : []), ...deps]);
}

export async function startDev() {
    // 1. Backend: idempotent installer brings up Postgres + api-server, seeds the user and
    //    verifies. A failure is logged to dazl-setup/root/install.log and reported here, and the
    //    dev server still starts so the error is visible instead of the hook timing out.
    const code = await runToEnd('node', [INSTALLER, '--skip-web-install', '--json'], ROOT);
    if (code !== 0) {
        console.error(`[dazl.hooks] backend install/verify failed (exit ${code}); see dazl-setup/root/install.log`);
    }

    // 2. Editor dev server, through the Dazl-rendered wrapper config so visual editing works.
    const dotenv = readEnvFile(path.join(APP_ROOT, '.env'));
    const viteConfig = process.env['DAZL_VITE_CONFIG'];
    const args = ['dev', APP_ROOT, '--host', '--port', String(WEB_PORT), '--strictPort'];
    if (viteConfig) args.push('-c', viteConfig);
    else console.warn('[dazl.hooks] DAZL_VITE_CONFIG is not set; starting without the Dazl wrapper');
    // Run the binary directly and in its own process group. Through `npx` the server is a grandchild
    // (npm -> sh -> node); killing npx alone left react-router holding 4444, and the restart after a
    // config change then died with EADDRINUSE under --strictPort.
    const reactRouterBin = path.join(APP_ROOT, 'node_modules', '.bin', 'react-router');
    // vite evaluates the wrapper config from process.env before the app loads .env, so the values
    // the config-time plugins read (published-ports proxy, CORS allowlist, preview client URL) must
    // reach the child through the environment. .env values fill in only what the runner did not set.
    const fromDotenv: Record<string, string | undefined> = {};
    for (const key of ['DAZL_PUBLIC_DEV_SERVER_URL', 'DAZL_SITE_URL', 'LOCAL_ENGINE_URL_TEMPLATE', 'LOCAL_PREVIEW_URL_TEMPLATE', 'LOCAL_ENGINE_PORT']) {
        fromDotenv[key] = process.env[key] || dotenv[key];
    }
    const child = spawn(reactRouterBin, args, {
        cwd: APP_ROOT,
        env: env(fromDotenv),
        stdio: ['ignore', 'pipe', 'pipe'],
        detached: true,
    });
    const stopTree = () => {
        try {
            process.kill(-child.pid!, 'SIGTERM');
        } catch {
            child.kill('SIGTERM');
        }
    };
    process.once('SIGTERM', stopTree);
    process.once('exit', stopTree);
    let boundPort: number | undefined;
    const onData = (buf: Buffer) => {
        const text = buf.toString();
        process.stdout.write(text);
        const m = /Local:\s+https?:\/\/[^:]+:(\d+)/.exec(text);
        if (m) boundPort = Number(m[1]);
    };
    child.stdout.on('data', onData);
    child.stderr.on('data', (b: Buffer) => process.stderr.write(b));

    let exited: number | null = null;
    let ready = false;
    child.on('exit', (c) => {
        exited = c ?? -1;
        if (ready) {
            // the runner only watches this hook process; surface a post-readiness crash instead of
            // letting Dazl believe the dev server is still up
            console.error(`[dazl.hooks] react-router dev exited with ${exited} after it was ready`);
            process.exit(exited || 1);
        }
    });

    const deadline = Date.now() + 5 * 60 * 1000;
    while (Date.now() < deadline) {
        if (exited !== null) throw new Error(`react-router dev exited with ${exited} before listening`);
        if (boundPort && (await portOpen(boundPort))) break;
        await new Promise((r) => setTimeout(r, 1000));
    }
    if (!boundPort) throw new Error('react-router dev did not report its port within 5 minutes');
    ready = true;
    return {
        port: boundPort,
        stop: () => {
            ready = false;
            stopTree();
        },
    };
}
